// Generated by scripts/notebooks_manifest.py. Do not edit by hand.
// Regenerate with `bun run data` from the site directory.

export type RunMode = 'interactive' | 'results' | 'source';

export const RUN_MODES: RunMode[] = ['interactive', 'results', 'source'];

export interface Notebook {
  title: string;
  summary: string;
  slug: string;
  path: string;
  export: boolean;
  mode: RunMode;
  sourceUrl: string;
  assetPath: string;
}

export interface Section {
  id: string;
  title: string;
  notebooks: Notebook[];
}

export interface Course {
  id: string;
  title: string;
  folderUrl: string;
  sections: Section[];
}

export interface Site {
  title: string;
  description: string;
  repository: string;
}

export const site: Site = {
  "title": "Notebooks",
  "description": "Cuadernos de fisica computacional: metodos numericos, sistemas dinamicos, mecanica estadistica y teledeteccion.",
  "repository": "https://github.com/totallynotdavid/undergrad"
};

export const courses: Course[] = [
  {
    "id": "fisica-general",
    "title": "Fisica general",
    "folderUrl": "https://github.com/totallynotdavid/undergrad/tree/master/packages/fisica-general",
    "sections": [
      {
        "id": "pendulos",
        "title": "Pendulos",
        "notebooks": [
          {
            "title": "Pendulo doble acoplado",
            "summary": "Dos angulos acoplados integrados con Euler explicito, con la acumulacion de error que el metodo introduce.",
            "slug": "fisica-general/pendulos/pendulo-doble",
            "path": "packages/fisica-general/pendulo_doble.py",
            "export": true,
            "mode": "interactive",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-general/pendulo_doble.py",
            "assetPath": "/notebooks/fisica-general/pendulos/pendulo-doble/"
          }
        ]
      }
    ]
  },
  {
    "id": "fisica-computacional",
    "title": "Fisica computacional",
    "folderUrl": "https://github.com/totallynotdavid/undergrad/tree/master/packages/fisica-computacional",
    "sections": [
      {
        "id": "metodos-numericos",
        "title": "Metodos numericos",
        "notebooks": [
          {
            "title": "Pendulo simple",
            "summary": "Oscilador no lineal integrado numericamente y su limite de pequenas oscilaciones.",
            "slug": "fisica-computacional/metodos-numericos/pendulo-simple",
            "path": "packages/fisica-computacional/metodos-numericos/pendulos-y-osciladores/pendulo_simple.py",
            "export": true,
            "mode": "interactive",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-computacional/metodos-numericos/pendulos-y-osciladores/pendulo_simple.py",
            "assetPath": "/notebooks/fisica-computacional/metodos-numericos/pendulo-simple/"
          },
          {
            "title": "Pendulo doble",
            "summary": "Sistema caotico de dos grados de libertad y su dependencia sensible de las condiciones iniciales.",
            "slug": "fisica-computacional/metodos-numericos/pendulo-doble",
            "path": "packages/fisica-computacional/metodos-numericos/pendulos-y-osciladores/pendulo_doble.py",
            "export": true,
            "mode": "interactive",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-computacional/metodos-numericos/pendulos-y-osciladores/pendulo_doble.py",
            "assetPath": "/notebooks/fisica-computacional/metodos-numericos/pendulo-doble/"
          },
          {
            "title": "EDP de calor en una dimension",
            "summary": "Diferencias finitas explicitas para la ecuacion de calor 1D y su condicion de estabilidad.",
            "slug": "fisica-computacional/metodos-numericos/edp-calor",
            "path": "packages/fisica-computacional/metodos-numericos/edp/edp_calor.py",
            "export": true,
            "mode": "interactive",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-computacional/metodos-numericos/edp/edp_calor.py",
            "assetPath": "/notebooks/fisica-computacional/metodos-numericos/edp-calor/"
          },
          {
            "title": "Integracion de Monte Carlo",
            "summary": "Estimador de Monte Carlo, su error estadistico que decae como 1/sqrt(N), y contraste con una rutina local en Fortran.",
            "slug": "fisica-computacional/metodos-numericos/monte-carlo",
            "path": "packages/fisica-computacional/metodos-numericos/monte-carlo/main.py",
            "export": true,
            "mode": "interactive",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-computacional/metodos-numericos/monte-carlo/main.py",
            "assetPath": "/notebooks/fisica-computacional/metodos-numericos/monte-carlo/"
          },
          {
            "title": "Monte Carlo con Fortran y f2py",
            "summary": "El mismo estimador de Monte Carlo enlazado a una rutina Fortran con f2py, como extension nativa local.",
            "slug": "fisica-computacional/metodos-numericos/monte-carlo-fortran",
            "path": "packages/fisica-computacional/metodos-numericos/monte-carlo/fortran_f2py.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-computacional/metodos-numericos/monte-carlo/fortran_f2py.py",
            "assetPath": ""
          }
        ]
      }
    ]
  },
  {
    "id": "fisica-moderna",
    "title": "Fisica moderna",
    "folderUrl": "https://github.com/totallynotdavid/undergrad/tree/master/packages/fisica-moderna",
    "sections": [
      {
        "id": "sistemas-dinamicos",
        "title": "Sistemas dinamicos",
        "notebooks": [
          {
            "title": "Atractor de Lorenz",
            "summary": "Sistema de Lorenz integrado en su regimen caotico y la geometria del atractor.",
            "slug": "fisica-moderna/sistemas-dinamicos/atractor-de-lorenz",
            "path": "packages/fisica-moderna/atractor_de_lorenz.py",
            "export": true,
            "mode": "interactive",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-moderna/atractor_de_lorenz.py",
            "assetPath": "/notebooks/fisica-moderna/sistemas-dinamicos/atractor-de-lorenz/"
          }
        ]
      },
      {
        "id": "radiacion",
        "title": "Radiacion",
        "notebooks": [
          {
            "title": "Curva de Planck",
            "summary": "Ley de Planck y los limites de Rayleigh-Jeans y Wien, con el calculo en Fortran local.",
            "slug": "fisica-moderna/radiacion/curva-de-planck",
            "path": "packages/fisica-moderna/curva-de-planck/main.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fisica-moderna/curva-de-planck/main.py",
            "assetPath": ""
          }
        ]
      }
    ]
  },
  {
    "id": "mecanica-estadistica",
    "title": "Mecanica estadistica",
    "folderUrl": "https://github.com/totallynotdavid/undergrad/tree/master/packages/mecanica-estadistica",
    "sections": [
      {
        "id": "monte-carlo",
        "title": "Monte Carlo",
        "notebooks": [
          {
            "title": "Volumen de la hiperesfera",
            "summary": "Estimacion Monte Carlo del volumen de la bola unitaria en n dimensiones y su decaimiento con la dimension.",
            "slug": "mecanica-estadistica/monte-carlo/volumen-hiperesfera",
            "path": "packages/mecanica-estadistica/calcular_volumen_esfera_n_dimensiones.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/mecanica-estadistica/calcular_volumen_esfera_n_dimensiones.py",
            "assetPath": ""
          },
          {
            "title": "Modelo de Ising 3D",
            "summary": "Algoritmo de Metropolis para el modelo de Ising 3D, con la magnetizacion y la transicion de fase.",
            "slug": "mecanica-estadistica/monte-carlo/modelo-de-ising",
            "path": "packages/mecanica-estadistica/modelo_de_ising.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/mecanica-estadistica/modelo_de_ising.py",
            "assetPath": ""
          }
        ]
      }
    ]
  },
  {
    "id": "inteligencia-artificial",
    "title": "Inteligencia artificial",
    "folderUrl": "https://github.com/totallynotdavid/undergrad/tree/master/packages/inteligencia-artificial",
    "sections": [
      {
        "id": "datos-tabulares",
        "title": "Datos tabulares",
        "notebooks": [
          {
            "title": "Limpieza de datos tabulares",
            "summary": "Limpieza y codificacion de variables sobre datos tabulares, con el dataset Titanic.",
            "slug": "inteligencia-artificial/datos-tabulares/limpieza-datos-tabulares",
            "path": "packages/inteligencia-artificial/limpieza_datos_tabulares.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/inteligencia-artificial/limpieza_datos_tabulares.py",
            "assetPath": ""
          }
        ]
      }
    ]
  },
  {
    "id": "tecnicas-de-teledeteccion",
    "title": "Tecnicas de teledeteccion",
    "folderUrl": "https://github.com/totallynotdavid/undergrad/tree/master/packages/tecnicas-de-teledeteccion",
    "sections": [
      {
        "id": "earth-engine-y-6s",
        "title": "Earth Engine y 6S",
        "notebooks": [
          {
            "title": "Clase 0: Py6S",
            "summary": "Transferencia radiativa atmosferica con el modelo 6S a traves de Py6S.",
            "slug": "tecnicas-de-teledeteccion/earth-engine-y-6s/clase-0-py6s",
            "path": "packages/tecnicas-de-teledeteccion/earth-engine-y-6s/clase_0_py6s.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/tecnicas-de-teledeteccion/earth-engine-y-6s/clase_0_py6s.py",
            "assetPath": ""
          },
          {
            "title": "Clase 1: Earth Engine",
            "summary": "Acceso y procesamiento de imagenes satelitales con Google Earth Engine.",
            "slug": "tecnicas-de-teledeteccion/earth-engine-y-6s/clase-1-earth-engine",
            "path": "packages/tecnicas-de-teledeteccion/earth-engine-y-6s/clase_1_earth_engine.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/tecnicas-de-teledeteccion/earth-engine-y-6s/clase_1_earth_engine.py",
            "assetPath": ""
          }
        ]
      },
      {
        "id": "raster-y-gdal",
        "title": "Raster y GDAL",
        "notebooks": [
          {
            "title": "Clase 2: GDAL",
            "summary": "Lectura y manipulacion de rasteres Landsat con GDAL.",
            "slug": "tecnicas-de-teledeteccion/raster-y-gdal/clase-2-gdal",
            "path": "packages/tecnicas-de-teledeteccion/raster-y-gdal/clase_2_gdal.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/tecnicas-de-teledeteccion/raster-y-gdal/clase_2_gdal.py",
            "assetPath": ""
          }
        ]
      },
      {
        "id": "correccion-atmosferica",
        "title": "Correccion atmosferica",
        "notebooks": [
          {
            "title": "Correccion atmosferica GaoFen-1",
            "summary": "Correccion atmosferica de imagenes GaoFen-1 con 6S y rasterio.",
            "slug": "tecnicas-de-teledeteccion/correccion-atmosferica/correccion-atmosferica-gaofen1",
            "path": "packages/tecnicas-de-teledeteccion/correccion-atmosferica-gaofen1/main.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/tecnicas-de-teledeteccion/correccion-atmosferica-gaofen1/main.py",
            "assetPath": ""
          }
        ]
      }
    ]
  },
  {
    "id": "fundamentos-de-riesgos-y-desastres",
    "title": "Fundamentos de riesgos y desastres",
    "folderUrl": "https://github.com/totallynotdavid/undergrad/tree/master/packages/fundamentos-de-riesgos-y-desastres",
    "sections": [
      {
        "id": "sigrid",
        "title": "SIGRID",
        "notebooks": [
          {
            "title": "Analisis de huaicos en Ancash",
            "summary": "Analisis geoespacial de huaicos en Ancash con geopandas sobre datos del SIGRID.",
            "slug": "fundamentos-de-riesgos-y-desastres/sigrid/huaicos-ancash",
            "path": "packages/fundamentos-de-riesgos-y-desastres/sigrid/analisis_huaicos_ancash.py",
            "export": false,
            "mode": "source",
            "sourceUrl": "https://github.com/totallynotdavid/undergrad/blob/master/packages/fundamentos-de-riesgos-y-desastres/sigrid/analisis_huaicos_ancash.py",
            "assetPath": ""
          }
        ]
      }
    ]
  }
];
