[project]
name = "undergrad"
version = "0.1.0"
readme = "readme.txt"
requires-python = ">=3.10, <3.14"
dependencies = []

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "notebooks" },
]
lint = [
    "ruff>=0.15.17",
]
notebooks = [
    "marimo>=0.23.15",
]
