[project]
name = "undergrad"
version = "0.1.0"
readme = "readme.txt"
requires-python = ">=3.10, <3.14"
dependencies = []

[tool.uv.workspace]
members = [
    "dinamica-molecular",
    "física-computacional",
    "física-general",
    "física-moderna",
    "inteligencia-artificial",
    "mecánica-estadística",
    "introduccion-a-sismologia",
    "técnicas-de-teledetección",
    "fundamentos-de-riesgos-y-desastres",
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
