from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

import tomllib

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "notebooks.toml"
SITE_DIR = ROOT / "site"
GENERATED_DATA = SITE_DIR / "src" / "lib" / "catalog.generated.ts"

SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:[-/][a-z0-9]+)*$")

MODE_ORDER = ("interactive", "results", "source")
VALID_MODES = set(MODE_ORDER)
ASSET_MODES = {"interactive", "results"}


@dataclass(frozen=True)
class SiteConfig:
    title: str
    description: str
    repository: str
    branch: str


@dataclass(frozen=True)
class Notebook:
    course_id: str
    course: str
    section_id: str
    section: str
    title: str
    summary: str
    path: str
    package: str
    package_dir: str
    slug: str
    export: bool
    mode: str


def load_manifest() -> tuple[SiteConfig, list[Notebook]]:
    with MANIFEST.open("rb") as file:
        data = tomllib.load(file)

    site_data = data["site"]
    site = SiteConfig(
        title=site_data["title"],
        description=site_data["description"],
        repository=site_data["repository"].rstrip("/"),
        branch=site_data["branch"],
    )
    root = data.get("defaults", {}).get("root", "notebooks").strip("/")
    notebooks = expand_notebooks(root, data.get("courses", []))
    return site, notebooks


def expand_notebooks(root: str, courses: list[dict]) -> list[Notebook]:
    notebooks: list[Notebook] = []
    for course in courses:
        course_id = course["id"]
        package = course.get("package", course_id)
        for section in course.get("sections", []):
            section_id = section["id"]
            for entry in section.get("notebooks", []):
                notebook_id = entry["id"]
                file_path = entry["file"].strip("/")
                export = entry["export"]
                mode = entry.get("mode") or ("interactive" if export else "source")
                notebooks.append(
                    Notebook(
                        course_id=course_id,
                        course=course["title"],
                        section_id=section_id,
                        section=section["title"],
                        title=entry["title"],
                        summary=entry["summary"],
                        path=f"{root}/{package}/{file_path}",
                        package=package,
                        package_dir=f"{root}/{package}",
                        slug=f"{course_id}/{section_id}/{notebook_id}",
                        export=export,
                        mode=mode,
                    )
                )
    return notebooks


def validate_manifest(notebooks: list[Notebook]) -> None:
    slugs: set[str] = set()
    paths: set[str] = set()
    errors: list[str] = []

    for notebook in notebooks:
        if notebook.slug in slugs:
            errors.append(f"Duplicate slug: {notebook.slug}")
        slugs.add(notebook.slug)

        if notebook.path in paths:
            errors.append(f"Duplicate path: {notebook.path}")
        paths.add(notebook.path)

        if not SLUG_PATTERN.fullmatch(notebook.slug):
            errors.append(f"Invalid slug: {notebook.slug}")

        if Path(notebook.path).is_absolute() or ".." in Path(notebook.path).parts:
            errors.append(f"Invalid notebook path: {notebook.path}")

        notebook_path = ROOT / notebook.path
        if not notebook_path.exists():
            errors.append(f"Missing notebook: {notebook.path}")

        if notebook.export and not notebook.package:
            errors.append(f"Missing package for exported notebook: {notebook.path}")

        if notebook.mode not in VALID_MODES:
            errors.append(f"Invalid mode '{notebook.mode}': {notebook.path}")
        elif notebook.export != (notebook.mode in ASSET_MODES):
            errors.append(
                f"Mode '{notebook.mode}' conflicts with export={notebook.export}: "
                f"{notebook.path}"
            )

    if errors:
        raise SystemExit("\n".join(errors))


def ts_header() -> str:
    union = " | ".join(f"'{mode}'" for mode in MODE_ORDER)
    array = ", ".join(f"'{mode}'" for mode in MODE_ORDER)
    return f"""// Generated by scripts/notebooks_manifest.py. Do not edit by hand.
// Regenerate with `bun run data` from the site directory.

export type RunMode = {union};

export const RUN_MODES: RunMode[] = [{array}];

export interface Notebook {{
  title: string;
  summary: string;
  slug: string;
  path: string;
  export: boolean;
  mode: RunMode;
  sourceUrl: string;
  assetPath: string;
}}

export interface Section {{
  id: string;
  title: string;
  notebooks: Notebook[];
}}

export interface Course {{
  id: string;
  title: string;
  folderUrl: string;
  sections: Section[];
}}

export interface Site {{
  title: string;
  description: string;
  repository: string;
}}

"""


def write_frontend_data(site: SiteConfig, notebooks: list[Notebook]) -> None:
    GENERATED_DATA.parent.mkdir(parents=True, exist_ok=True)
    site_public = {
        "title": site.title,
        "description": site.description,
        "repository": site.repository,
    }
    site_ts = json.dumps(site_public, ensure_ascii=False, indent=2)
    courses_ts = json.dumps(
        build_courses(site, notebooks), ensure_ascii=False, indent=2
    )
    content = (
        ts_header()
        + f"export const site: Site = {site_ts};\n\n"
        + f"export const courses: Course[] = {courses_ts};\n"
    )
    GENERATED_DATA.write_text(content, encoding="utf-8")


def build_courses(site: SiteConfig, notebooks: list[Notebook]) -> list[dict]:
    courses: list[dict] = []
    for notebook in notebooks:
        course = _find(courses, notebook.course_id)
        if course is None:
            course = {
                "id": notebook.course_id,
                "title": notebook.course,
                "folderUrl": folder_url(site, notebook),
                "sections": [],
            }
            courses.append(course)

        section = _find(course["sections"], notebook.section_id)
        if section is None:
            section = {
                "id": notebook.section_id,
                "title": notebook.section,
                "notebooks": [],
            }
            course["sections"].append(section)

        section["notebooks"].append(notebook_data(site, notebook))
    return courses


def _find(items: list[dict], item_id: str) -> dict | None:
    return next((item for item in items if item["id"] == item_id), None)


def notebook_data(site: SiteConfig, notebook: Notebook) -> dict:
    return {
        "title": notebook.title,
        "summary": notebook.summary,
        "slug": notebook.slug,
        "path": notebook.path,
        "export": notebook.export,
        "mode": notebook.mode,
        "sourceUrl": source_url(site, notebook),
        "assetPath": f"/notebooks/{notebook.slug}/" if notebook.export else "",
    }


def source_url(site: SiteConfig, notebook: Notebook) -> str:
    encoded_path = quote(notebook.path)
    return f"{site.repository}/blob/{site.branch}/{encoded_path}"


def folder_url(site: SiteConfig, notebook: Notebook) -> str:
    encoded_dir = quote(notebook.package_dir)
    return f"{site.repository}/tree/{site.branch}/{encoded_dir}"
